version: "3.7"

# USAGE:
# Create and start the cluster: docker-compose up -d
# Tear down the cluster: docker-compose down
# Reove everything including the volumes: docker-compose down -v
services:
  ftp:
    image: bogem/ftp
    hostname: ftp
    container_name: ftp
    restart: always
    volumes:
      - img-data:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      FTP_USER: dahua
      PASV_ADDRESS: 10.29.167.244
      FTP_PASS: dahua
    network_mode: bridge
    logging:
      driver: syslog
      options:
        tag: docker/ftp

  notify:
    build:
      context: js-line-notify/
    hostname: linenotify
    container_name: notify
    restart: always
    volumes:
      - img-data:/usr/src/app/img
    network_mode: bridge
    logging:
      driver: syslog
      options:
        tag: docker/linenotify

volumes:
  img-data:
